// Mocks generated by Mockito 5.0.10 from annotations
// in rick_morty_and_flutter/test/modules/home/data/repositories/character_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rick_morty_and_flutter/modules/character/data/sources/character_remote_data_source.dart'
    as _i2;
import 'package:rick_morty_and_flutter/modules/character/domain/entities/character.dart'
    as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [CharacterRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterRemoteDataSource extends _i1.Mock
    implements _i2.CharacterRemoteDataSource {
  MockCharacterRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Character>> getCharacters() =>
      (super.noSuchMethod(Invocation.method(#getCharacters, []),
              returnValue: Future<List<_i4.Character>>.value(<_i4.Character>[]))
          as _i3.Future<List<_i4.Character>>);
}
